/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ClassicosRouteImport } from './routes/classicos'
import { Route as ExplorarRouteImport } from './routes/explorar'
import { Route as IndicacoesRouteImport } from './routes/indicacoes'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TendenciasRouteImport } from './routes/tendencias'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedGerenciarRouteImport } from './routes/_authenticated/gerenciar'
import { Route as AuthenticatedMeuRouteImport } from './routes/_authenticated/meu'
import { Route as CCategoryRouteImport } from './routes/c.$category'
import { Route as ClassicoIdRouteImport } from './routes/classico.$id'
import { Route as TitleSourceTypeIdRouteImport } from './routes/title.$source.$type.$id'
import { Route as WatchSourceTypeIdRouteImport } from './routes/watch.$source.$type.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassicosRoute = ClassicosRouteImport.update({
  id: '/classicos',
  path: '/classicos',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorarRoute = ExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicacoesRoute = IndicacoesRouteImport.update({
  id: '/indicacoes',
  path: '/indicacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TendenciasRoute = TendenciasRouteImport.update({
  id: '/tendencias',
  path: '/tendencias',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGerenciarRoute = AuthenticatedGerenciarRouteImport.update({
  id: '/gerenciar',
  path: '/gerenciar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeuRoute = AuthenticatedMeuRouteImport.update({
  id: '/meu',
  path: '/meu',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CCategoryRoute = CCategoryRouteImport.update({
  id: '/c/$category',
  path: '/c/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassicoIdRoute = ClassicoIdRouteImport.update({
  id: '/classico/$id',
  path: '/classico/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TitleSourceTypeIdRoute = TitleSourceTypeIdRouteImport.update({
  id: '/title/$source/$type/$id',
  path: '/title/$source/$type/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchSourceTypeIdRoute = WatchSourceTypeIdRouteImport.update({
  id: '/watch/$source/$type/$id',
  path: '/watch/$source/$type/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/classicos': typeof ClassicosRoute
  '/explorar': typeof ExplorarRoute
  '/indicacoes': typeof IndicacoesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tendencias': typeof TendenciasRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/gerenciar': typeof AuthenticatedGerenciarRoute
  '/meu': typeof AuthenticatedMeuRoute
  '/c/$category': typeof CCategoryRoute
  '/classico/$id': typeof ClassicoIdRoute
  '/title/$source/$type/$id': typeof TitleSourceTypeIdRoute
  '/watch/$source/$type/$id': typeof WatchSourceTypeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/classicos': typeof ClassicosRoute
  '/explorar': typeof ExplorarRoute
  '/indicacoes': typeof IndicacoesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tendencias': typeof TendenciasRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/gerenciar': typeof AuthenticatedGerenciarRoute
  '/meu': typeof AuthenticatedMeuRoute
  '/c/$category': typeof CCategoryRoute
  '/classico/$id': typeof ClassicoIdRoute
  '/title/$source/$type/$id': typeof TitleSourceTypeIdRoute
  '/watch/$source/$type/$id': typeof WatchSourceTypeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/classicos': typeof ClassicosRoute
  '/explorar': typeof ExplorarRoute
  '/indicacoes': typeof IndicacoesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tendencias': typeof TendenciasRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/gerenciar': typeof AuthenticatedGerenciarRoute
  '/_authenticated/meu': typeof AuthenticatedMeuRoute
  '/c/$category': typeof CCategoryRoute
  '/classico/$id': typeof ClassicoIdRoute
  '/title/$source/$type/$id': typeof TitleSourceTypeIdRoute
  '/watch/$source/$type/$id': typeof WatchSourceTypeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/classicos'
    | '/explorar'
    | '/indicacoes'
    | '/reset-password'
    | '/tendencias'
    | '/admin'
    | '/gerenciar'
    | '/meu'
    | '/c/$category'
    | '/classico/$id'
    | '/title/$source/$type/$id'
    | '/watch/$source/$type/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/classicos'
    | '/explorar'
    | '/indicacoes'
    | '/reset-password'
    | '/tendencias'
    | '/admin'
    | '/gerenciar'
    | '/meu'
    | '/c/$category'
    | '/classico/$id'
    | '/title/$source/$type/$id'
    | '/watch/$source/$type/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/classicos'
    | '/explorar'
    | '/indicacoes'
    | '/reset-password'
    | '/tendencias'
    | '/_authenticated/admin'
    | '/_authenticated/gerenciar'
    | '/_authenticated/meu'
    | '/c/$category'
    | '/classico/$id'
    | '/title/$source/$type/$id'
    | '/watch/$source/$type/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ClassicosRoute: typeof ClassicosRoute
  ExplorarRoute: typeof ExplorarRoute
  IndicacoesRoute: typeof IndicacoesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TendenciasRoute: typeof TendenciasRoute
  CCategoryRoute: typeof CCategoryRoute
  ClassicoIdRoute: typeof ClassicoIdRoute
  TitleSourceTypeIdRoute: typeof TitleSourceTypeIdRoute
  WatchSourceTypeIdRoute: typeof WatchSourceTypeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classicos': {
      id: '/classicos'
      path: '/classicos'
      fullPath: '/classicos'
      preLoaderRoute: typeof ClassicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorar': {
      id: '/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof ExplorarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indicacoes': {
      id: '/indicacoes'
      path: '/indicacoes'
      fullPath: '/indicacoes'
      preLoaderRoute: typeof IndicacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tendencias': {
      id: '/tendencias'
      path: '/tendencias'
      fullPath: '/tendencias'
      preLoaderRoute: typeof TendenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gerenciar': {
      id: '/_authenticated/gerenciar'
      path: '/gerenciar'
      fullPath: '/gerenciar'
      preLoaderRoute: typeof AuthenticatedGerenciarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meu': {
      id: '/_authenticated/meu'
      path: '/meu'
      fullPath: '/meu'
      preLoaderRoute: typeof AuthenticatedMeuRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/c/$category': {
      id: '/c/$category'
      path: '/c/$category'
      fullPath: '/c/$category'
      preLoaderRoute: typeof CCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classico/$id': {
      id: '/classico/$id'
      path: '/classico/$id'
      fullPath: '/classico/$id'
      preLoaderRoute: typeof ClassicoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/title/$source/$type/$id': {
      id: '/title/$source/$type/$id'
      path: '/title/$source/$type/$id'
      fullPath: '/title/$source/$type/$id'
      preLoaderRoute: typeof TitleSourceTypeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$source/$type/$id': {
      id: '/watch/$source/$type/$id'
      path: '/watch/$source/$type/$id'
      fullPath: '/watch/$source/$type/$id'
      preLoaderRoute: typeof WatchSourceTypeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedGerenciarRoute: typeof AuthenticatedGerenciarRoute
  AuthenticatedMeuRoute: typeof AuthenticatedMeuRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedGerenciarRoute: AuthenticatedGerenciarRoute,
  AuthenticatedMeuRoute: AuthenticatedMeuRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ClassicosRoute: ClassicosRoute,
  ExplorarRoute: ExplorarRoute,
  IndicacoesRoute: IndicacoesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TendenciasRoute: TendenciasRoute,
  CCategoryRoute: CCategoryRoute,
  ClassicoIdRoute: ClassicoIdRoute,
  TitleSourceTypeIdRoute: TitleSourceTypeIdRoute,
  WatchSourceTypeIdRoute: WatchSourceTypeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
